// Mocks generated by Mockito 5.4.0 from annotations
// in classroom_app/test/features/landing/presentation/providers/landing_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:classroom_app/core/entities/courses.dart' as _i7;
import 'package:classroom_app/core/error/failures.dart' as _i6;
import 'package:classroom_app/core/use_cases/use_case.dart' as _i8;
import 'package:classroom_app/core/utils/utils.dart' as _i9;
import 'package:classroom_app/features/landing/domain/repositories/landing_repository.dart'
    as _i2;
import 'package:classroom_app/features/landing/domain/usecases/get_courses.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLandingRepository_0 extends _i1.SmartFake
    implements _i2.LandingRepository {
  _FakeLandingRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCourses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCourses extends _i1.Mock implements _i4.GetCourses {
  @override
  _i2.LandingRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLandingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeLandingRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LandingRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Courses>> call(
          _i8.NoParams? noParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [noParams],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Courses>>.value(
            _FakeEither_1<_i6.Failure, _i7.Courses>(
          this,
          Invocation.method(
            #call,
            [noParams],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.Courses>>.value(
                _FakeEither_1<_i6.Failure, _i7.Courses>(
          this,
          Invocation.method(
            #call,
            [noParams],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Courses>>);
}

/// A class which mocks [Utils].
///
/// See the documentation for Mockito's code generation for more information.
class MockUtils extends _i1.Mock implements _i9.Utils {}
